### ISSUE TITLE
Lookups performance

### ISSUE THREAD

**Issue by Fnux** [Fnux/hanabi#8]
There's a lot of lookups and some of them are highly inefficient. The best example is `Hanabi.User.get_by/2` : 
```
def get_by(field, value) do
  result = Enum.find(get_all(), fn([{_,user}]) -> Map.get(user, field) == value end)
  if result do
    {_key, user} = List.first(result)
    user
  else
    nil
  end
end
```

It's okay with a few users but not a proper solution. 

Due to the nature of IRC, there is a lot (most of them) of lookups using the nickname of an user. How about an ETS table matching nicknames to user keys ?

**Comment by andreapavoni** [comment]
**disclaimer:** I’ve just discovered this interesting project, I still haven’t sern the code and ideas behind its logic.

Having an ETS table to handle conmected users seems a good solution, pretty faster for sure ;-)

Maybe you could use the username for key and the user process pid as value. At least, it would return the entire process so that you can interact with it, rather than getting the User struct

**Comment by Fnux** [comment]
You often have to resolve an user given its *current* nickname : I don't get why your solution would be faster. Or is it to be combined with the nickname<->key table ?

Thank you for your interest!

**Comment by andreapavoni** [comment]
I apologise for my bad wording :-P

First of all, I think ETS would be perfect for perfomances, rather than doing lookups in the current way.

My other hypothesis is to use `username` as key for ETS table, and the `pid` of the user process as value rather than using the User struct. This is a different approach (and I don't think it would necessarily improve perfomance). But, just in case, having the User pid would let to send OTP messages to the User process.

This should (again, only in theory, because I didn't see all the code and the logic yet) help in two ways:

* you can do some actions in async (eg: broadcast messages without waiting for finish)
* you can update the User struct because it's parth of the user process state (eg: change nick)

my 2 cents. I'll try to dive deeper in your code and eventually update this comment :-P

keep up the good work!

**Comment by Fnux** [comment]
Well, I haven't touched this project for the last ~2months.

Please note that :
* Since the user process looks into the registry, it's not an issue to modify the user struct.
* The pid of the user process is available in the Use struct.

I already modified the `Hanabi.Registry` module to use ETS (some time ago). I guess I should now use something like `:ets.match/2` [0] to improve the performance of the lookups.

Sadly, I won't have enough time to work on this project for the next 2 weeks.

[0] http://erlang.org/doc/man/ets.html#match-2

**Comment by andreapavoni** [comment]
Oh, I see! Then, storing the User struct would be a much better solution ;-P

However, why `etc.match/2` rather than `ets.lookup/2`[0]? It looks like the latter would be more appropriate considering that nicknames are unique and you just don't need to match similar nicknames. Am I wrong?

[0] http://erlang.org/doc/man/ets.html#lookup-2

**Comment by Fnux** [comment]
An IRC nickname may change, you can't use it for the key. The idea behind `ets.match/2` is to match the User struct stored in the ETS table as a value.

**Comment by Fnux** [comment]
Due to 30c7783bdff5215a37e3589507236aa04bc61ad4, `User.get_by/2` now uses `:ets.match/3` for the lookup. It should be faster since it doesn't have to go through the whole table anymore.

I guess it's enough for now. I close the issue.
